# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PruebaAtento\TemporizarVista.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MonitorVista(object):
    def setupUi(self, MonitorVista):
        MonitorVista.setObjectName("MonitorVista")
        MonitorVista.resize(450, 469)
        self.centralwidget = QtWidgets.QWidget(MonitorVista)
        self.centralwidget.setObjectName("centralwidget")
        self.tblVista = QtWidgets.QTableWidget(self.centralwidget)
        self.tblVista.setGeometry(QtCore.QRect(20, 51, 411, 301))
        self.tblVista.setObjectName("tblVista")
        self.tblVista.setColumnCount(4)
        self.tblVista.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblVista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVista.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVista.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVista.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 15, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(54, 132, 185);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnMostrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnMostrar.setGeometry(QtCore.QRect(230, 370, 101, 23))
        self.btnMostrar.setObjectName("btnMostrar")
        self.btnBorrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBorrar.setGeometry(QtCore.QRect(110, 370, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnBorrar.setFont(font)
        self.btnBorrar.setObjectName("btnBorrar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 420, 391, 20))
        self.label_4.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 440, 411, 20))
        self.label_5.setStyleSheet("color: rgb(0, 85, 127);\n"
"color: rgb(255, 85, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MonitorVista.setCentralWidget(self.centralwidget)

        self.retranslateUi(MonitorVista)
        QtCore.QMetaObject.connectSlotsByName(MonitorVista)

    def retranslateUi(self, MonitorVista):
        _translate = QtCore.QCoreApplication.translate
        MonitorVista.setWindowTitle(_translate("MonitorVista", "VISTA TEMPORIZADOR"))
        item = self.tblVista.horizontalHeaderItem(0)
        item.setText(_translate("MonitorVista", "CodCinta"))
        item = self.tblVista.horizontalHeaderItem(1)
        item.setText(_translate("MonitorVista", "Titulo_Cinta"))
        item = self.tblVista.horizontalHeaderItem(2)
        item.setText(_translate("MonitorVista", "Genero"))
        item = self.tblVista.horizontalHeaderItem(3)
        item.setText(_translate("MonitorVista", "Año"))
        self.label.setText(_translate("MonitorVista", "TEMPORIZADOR DE VISTA"))
        self.btnMostrar.setText(_translate("MonitorVista", "MOSTRAR"))
        self.btnBorrar.setText(_translate("MonitorVista", "BORRAR"))
        self.label_4.setText(_translate("MonitorVista", "Desarrollador: Jonathan Vera Segura"))
        self.label_5.setText(_translate("MonitorVista", "Empresa: Anonimo"))
